{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f164d8f1-87c4-4dd0-9fb2-3dd1a737e025",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================\n",
    "# Player Information Window\n",
    "# ==========================================\n",
    "\n",
    "import tkinter as tk\n",
    "\n",
    "\n",
    "def player_info():\n",
    "    \"\"\"\n",
    "    Creates a window where two players\n",
    "    can enter their names.\n",
    "    \"\"\"\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Create the main window\n",
    "    # ------------------------------------------\n",
    "    player_window = tk.Tk()\n",
    "\n",
    "    player_window.title(\"Player Information\")\n",
    "    player_window.geometry(\"500x250+100+100\")\n",
    "    player_window.configure(bg=\"lightblue\")\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Variables to store player names\n",
    "    # ------------------------------------------\n",
    "    player1_name_var = tk.StringVar()\n",
    "    player2_name_var = tk.StringVar()\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Heading\n",
    "    # ------------------------------------------\n",
    "    heading_label = tk.Label(\n",
    "        player_window,\n",
    "        text=\"Enter Player Names\",\n",
    "        font=(\"Times\", 20, \"bold\"),\n",
    "        bg=\"lightblue\",\n",
    "        fg=\"black\"\n",
    "    )\n",
    "    heading_label.grid(row=0, column=0, columnspan=2, pady=20)\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Player 1 Label\n",
    "    # ------------------------------------------\n",
    "    player1_label = tk.Label(\n",
    "        player_window,\n",
    "        text=\"Player 1\",\n",
    "        font=(\"Times\", 14, \"bold\"),\n",
    "        bg=\"black\",\n",
    "        fg=\"white\",\n",
    "        width=10\n",
    "    )\n",
    "    player1_label.grid(row=1, column=0, padx=20, pady=10)\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Player 1 Name Entry Box\n",
    "    # ------------------------------------------\n",
    "    player1_entry = tk.Entry(\n",
    "        player_window,\n",
    "        textvariable=player1_name_var,\n",
    "        width=20\n",
    "    )\n",
    "    player1_entry.grid(row=2, column=0, padx=20)\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Player 2 Label\n",
    "    # ------------------------------------------\n",
    "    player2_label = tk.Label(\n",
    "        player_window,\n",
    "        text=\"Player 2\",\n",
    "        font=(\"Times\", 14, \"bold\"),\n",
    "        bg=\"black\",\n",
    "        fg=\"white\",\n",
    "        width=10\n",
    "    )\n",
    "    player2_label.grid(row=1, column=1, padx=20, pady=10)\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Player 2 Name Entry Box\n",
    "    # ------------------------------------------\n",
    "    player2_entry = tk.Entry(\n",
    "        player_window,\n",
    "        textvariable=player2_name_var,\n",
    "        width=20\n",
    "    )\n",
    "    player2_entry.grid(row=2, column=1, padx=20)\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Function to display entered names\n",
    "    # ------------------------------------------\n",
    "    def submit_names():\n",
    "        print(\"Player 1:\", player1_name_var.get())\n",
    "        print(\"Player 2:\", player2_name_var.get())\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Submit Button\n",
    "    # ------------------------------------------\n",
    "    submit_button = tk.Button(\n",
    "        player_window,\n",
    "        text=\"Submit\",\n",
    "        command=submit_names,\n",
    "        bg=\"green\",\n",
    "        fg=\"white\",\n",
    "        font=(\"Arial\", 12, \"bold\")\n",
    "    )\n",
    "    submit_button.grid(row=3, column=0, columnspan=2, pady=30)\n",
    "\n",
    "    # ------------------------------------------\n",
    "    # Start the Tkinter event loop\n",
    "    # ------------------------------------------\n",
    "    player_window.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d430cad2-42f4-4afe-b307-eb2e25519283",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
